### ISSUE TITLE
Refactor home page with containers/components structure

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#243]
- [x] Move src/pages/home.js to src/containers/home.js [#245]
- [x] Move all child components of home.js into /src/components/legacy/ (components should not hold state) [#245]
- [x] Split searchbar.js into logic container and presentation component(s) — e.g. make longSearchBar and shortSearchBar components - Shaka [#248]
- [x] Split top-petitions.js into logic container and presentation component(s) — e.g. move wrapper div and header out of container. - Justin [#246]
- [x] Update home page tests - Justin, Shaka [#245]
