### ISSUE TITLE
Apply redesign to sign page

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/mop-frontend#309]
- [x] Overall page style (#305)
- [x] Design updates for the signature list (#307)
- [x] Add the mobile sign button and modal form (#322)
- [x] Working share buttons (#336)
- [x] "Thank you" page style (#333)
- [x] replace modal with inline form (#384 )
- [x]  petition messages (#383)
- [x] Thanks redirect message (#383)

**Comment by jparkrr** [comment]
Related issue for mobile signing: https://github.com/MoveOnOrg/giraffe/issues/76

**Comment by jparkrr** [comment]
The basic work has been done. We can file new issues if we find anything else to do.
