### ISSUE TITLE
MVP form tracking

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/mop-frontend#546]
This is a subset of tasks for #44  (though possibly does quite a bit)

The target goal is to track enough information so that we can deploy and compare PR #525 showing the phone field with SMS subscription and decide whether it's worth it.

It is based on [this proposal](https://docs.google.com/document/d/1Lo17jz475a0IBXRjY4xhRt19S6iZHiDrl8MRXI9pQmE/edit#) however, we don't need to track abandonment -- just form-start and form-completion

- [ ] Make a general method in src/lib/ that 
  - [ ] create a form-tracking object
  - [ ] which has methods for 1. updating form state, 2. sending a track event 3. initializing the form tracker with state
  - [ ] maybe a helper-method which updates the index based on the field name
- [ ] In the src/containers/signature-add-form.js container:
  - [ ] Create a form tracker when window.analytics exists in componentWillMount or something
  - [ ] inside updateStateFromValue
    - [ ] update the maximum field index changed (maybe use form.elements in javascript?)
    - [ ] update expansion count/moment (increment each time)
- [ ] Make sure you consider the case where someone is logged in/guested and there essentially are no fields and it will just complete if they click 'sign' -- for this reason, we want to track the login-state (not the user, but whether they're 'known' or not) in the form tracker as well.
- [ ] reading cohort for a particular test and tracking it in the tracker might be part of instantiation -- 
there may be useful plumbing for choosing a cohort randomly (that e.g. comes from #525 ) or following a cohort choice from query arguments that were included in e.g. a mailing.

Some use cases:
* A test that is only enabled when the query parameters are there (i.e. not from random traffic)
* Possibly keeping someone in the cohort they were chosen (via localStorage or cookie) over some period of time
* Randomly assigning a cohort as #525 does for random traffic.

**Comment by shakalee14** [comment]
@sandramchung - how does this sound?

**Comment by sandramchung** [comment]
Looks great. I'm excited to see it implemented, and then to extend it for the petition creation form.

**Comment by shakalee14** [comment]
Re-reading this @schuyler1d I believe some of this isnt MVP because it includes keeping up with the progress of the form (i.e. figuring out the point of drop off).

MVP should be tracking that the form was started and finished.

**Comment by shakalee14** [comment]
Deployed to broom --> fixed by #549
